import { Deck, Word, Profile } from '@/types/database.types';

export const MOCK_PROFILE: Profile = {
  id: 'guest-user-001',
  username: 'lingo_learner',
  display_name: 'LingoCat Learner',
  avatar_url: null,
  total_xp: 350,
  level: 2,
  streak_days: 3,
  last_played_at: new Date().toISOString(),
  highest_combo: 14,
  total_games_played: 5,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const MOCK_DECKS: Deck[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    creator_id: null,
    title: 'IELTS Core Power Words (Band 7.5+)',
    slug: 'ielts-core-power-words',
    description: 'Tuyển tập các từ vựng học thuật đỉnh cao giúp nâng band điểm Writing & Speaking trong kỳ thi IELTS.',
    category: 'Academic',
    difficulty: 'advanced',
    is_public: true,
    is_official: true,
    word_count: 10,
    icon_name: 'GraduationCap',
    color_gradient: 'from-purple-600 via-indigo-600 to-blue-600',
    play_count: 1280,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    creator_id: null,
    title: 'Cyberpunk & Tech Frontiers',
    slug: 'cyberpunk-and-tech-frontiers',
    description: 'Kho từ vựng công nghệ thế kỷ 22, lập trình, trí tuệ nhân tạo và an ninh mạng.',
    category: 'Technology',
    difficulty: 'intermediate',
    is_public: true,
    is_official: true,
    word_count: 10,
    icon_name: 'Cpu',
    color_gradient: 'from-cyan-500 via-teal-500 to-emerald-500',
    play_count: 2450,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    creator_id: null,
    title: 'Everyday Survival English',
    slug: 'everyday-survival-english',
    description: 'Các từ vựng thiết yếu nhất trong giao tiếp hàng ngày, du lịch và xử lý tình huống nhanh.',
    category: 'Conversational',
    difficulty: 'beginner',
    is_public: true,
    is_official: true,
    word_count: 8,
    icon_name: 'Compass',
    color_gradient: 'from-amber-500 via-orange-500 to-rose-500',
    play_count: 3100,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_WORDS: Record<string, Word[]> = {
  '11111111-1111-1111-1111-111111111111': [
    {
      id: 'w101',
      deck_id: '11111111-1111-1111-1111-111111111111',
      term: 'ABANDON',
      phonetic: '/əˈbæn.dən/',
      translation: 'Từ bỏ, ruồng bỏ',
      example_sentence: 'They had to abandon the sinking ship.',
      example_translation: 'Họ phải từ bỏ con tàu đang chìm.',
      audio_url: null,
      image_url: null,
      distractors: ['Duy trì', 'Xây dựng', 'Khen ngợi'],
      difficulty_level: 2,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w102',
      deck_id: '11111111-1111-1111-1111-111111111111',
      term: 'AMBIGUOUS',
      phonetic: '/æmˈbɪɡ.ju.əs/',
      translation: 'Mơ hồ, nước đôi',
      example_sentence: 'His reply to my question was somewhat ambiguous.',
      example_translation: 'Câu trả lời của anh ấy có phần mơ hồ.',
      distractors: ['Rõ ràng', 'Dứt khoát', 'Chân thành'],
      difficulty_level: 3,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w103',
      deck_id: '11111111-1111-1111-1111-111111111111',
      term: 'COMPREHENSIVE',
      phonetic: '/ˌkɒm.prɪˈhen.sɪv/',
      translation: 'Toàn diện, bao quát',
      example_sentence: 'The university offers a comprehensive study program.',
      example_translation: 'Trường cung cấp một chương trình học toàn diện.',
      distractors: ['Sơ sài', 'Ngắn gọn', 'Cục bộ'],
      difficulty_level: 3,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w104',
      deck_id: '11111111-1111-1111-1111-111111111111',
      term: 'DIVERSE',
      phonetic: '/daɪˈvɜːs/',
      translation: 'Đa dạng, phong phú',
      example_sentence: 'New York is a very culturally diverse city.',
      example_translation: 'New York là một thành phố rất đa dạng văn hóa.',
      distractors: ['Đơn điệu', 'Hạn hẹp', 'Lặp lại'],
      difficulty_level: 2,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w105',
      deck_id: '11111111-1111-1111-1111-111111111111',
      term: 'ELABORATE',
      phonetic: '/iˈlæb.ər.ət/',
      translation: 'Phức tạp, công phu',
      example_sentence: 'They made elaborate preparations for the festival.',
      example_translation: 'Họ đã chuẩn bị rất công phu cho lễ hội.',
      distractors: ['Đơn giản', 'Tùy tiện', 'Tạm thời'],
      difficulty_level: 3,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w106',
      deck_id: '11111111-1111-1111-1111-111111111111',
      term: 'FEASIBLE',
      phonetic: '/ˈfiː.zə.bəl/',
      translation: 'Khả thi, làm được',
      example_sentence: 'It is not feasible to build the bridge in one month.',
      example_translation: 'Không khả thi để xây cây cầu đó trong một tháng.',
      distractors: ['Bất khả thi', 'Vô lý', 'Nguy hiểm'],
      difficulty_level: 3,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w107',
      deck_id: '11111111-1111-1111-1111-111111111111',
      term: 'INNOVATIVE',
      phonetic: '/ˈɪn.ə.və.tɪv/',
      translation: 'Đột phá, đổi mới sáng tạo',
      example_sentence: 'The company is famous for its innovative tech products.',
      example_translation: 'Công ty nổi tiếng với các sản phẩm công nghệ đột phá.',
      distractors: ['Lạc hậu', 'Rập khuôn', 'Bảo thủ'],
      difficulty_level: 2,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w108',
      deck_id: '11111111-1111-1111-1111-111111111111',
      term: 'PRECISE',
      phonetic: '/prɪˈsaɪs/',
      translation: 'Chính xác, tỉ mỉ',
      example_sentence: 'Scientists need precise measurements for this experiment.',
      example_translation: 'Các nhà khoa học cần các phép đo chính xác.',
      distractors: ['Ước chừng', 'Mơ hồ', 'Sai lệch'],
      difficulty_level: 2,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w109',
      deck_id: '11111111-1111-1111-1111-111111111111',
      term: 'RESILIENT',
      phonetic: '/rɪˈzɪl.jənt/',
      translation: 'Kiên cường, phục hồi nhanh',
      example_sentence: 'Children are often remarkably resilient after tough events.',
      example_translation: 'Trẻ em thường kiên cường sau biến cố.',
      distractors: ['Yếu đuối', 'Dễ vỡ', 'Tuyệt vọng'],
      difficulty_level: 3,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w110',
      deck_id: '11111111-1111-1111-1111-111111111111',
      term: 'SUSTAINABLE',
      phonetic: '/səˈsteɪ.nə.bəl/',
      translation: 'Bền vững, lâu dài',
      example_sentence: 'We must focus on sustainable economic development.',
      example_translation: 'Chúng ta phải tập trung vào phát triển bền vững.',
      distractors: ['Tạm bợ', 'Tiêu hao', 'Gây hại'],
      difficulty_level: 2,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
  ],
  '22222222-2222-2222-2222-222222222222': [
    {
      id: 'w201',
      deck_id: '22222222-2222-2222-2222-222222222222',
      term: 'ALGORITHM',
      phonetic: '/ˈæl.ɡə.rɪ.ðəm/',
      translation: 'Thuật toán',
      example_sentence: 'The search engine uses a sophisticated ranking algorithm.',
      example_translation: 'Công cụ tìm kiếm sử dụng thuật toán xếp hạng tinh vi.',
      distractors: ['Phần cứng', 'Bàn phím', 'Dữ liệu thô'],
      difficulty_level: 1,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w202',
      deck_id: '22222222-2222-2222-2222-222222222222',
      term: 'AUTHENTICATION',
      phonetic: '/ɔːˌθen.tɪˈkeɪ.ʃən/',
      translation: 'Xác thực danh tính',
      example_sentence: 'Two-factor authentication adds an extra layer of security.',
      example_translation: 'Xác thực hai yếu tố bổ sung thêm một lớp bảo mật.',
      distractors: ['Mã hóa', 'Đăng xuất', 'Cài đặt'],
      difficulty_level: 2,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w203',
      deck_id: '22222222-2222-2222-2222-222222222222',
      term: 'BANDWIDTH',
      phonetic: '/ˈbænd.wɪtθ/',
      translation: 'Băng thông mạng',
      example_sentence: 'Streaming 4K video requires high bandwidth.',
      example_translation: 'Xem video 4K trực tuyến đòi hỏi băng thông cao.',
      distractors: ['Dung lượng pin', 'Màn hình', 'Âm lượng'],
      difficulty_level: 2,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w204',
      deck_id: '22222222-2222-2222-2222-222222222222',
      term: 'CYBERNETICS',
      phonetic: '/ˌsaɪ.bəˈnet.ɪks/',
      translation: 'Điều khiển học',
      example_sentence: 'He studied cybernetics to build responsive prosthetics.',
      example_translation: 'Anh nghiên cứu điều khiển học để chế tạo bộ phận giả.',
      distractors: ['Thực vật học', 'Địa chất học', 'Văn học'],
      difficulty_level: 4,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w205',
      deck_id: '22222222-2222-2222-2222-222222222222',
      term: 'ENCRYPTION',
      phonetic: '/ɪnˈkrɪp.ʃən/',
      translation: 'Mã hóa dữ liệu',
      example_sentence: 'End-to-end encryption keeps your messages private.',
      example_translation: 'Mã hóa đầu cuối giữ cho tin nhắn được bảo mật.',
      distractors: ['Sao lưu', 'Xóa bỏ', 'Giải mã công khai'],
      difficulty_level: 2,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w206',
      deck_id: '22222222-2222-2222-2222-222222222222',
      term: 'FRAMEWORK',
      phonetic: '/ˈfreɪm.wɜːk/',
      translation: 'Khung phần mềm / Nền tảng',
      example_sentence: 'Next.js is a powerful React framework for web apps.',
      example_translation: 'Next.js là một khung làm việc React mạnh mẽ.',
      distractors: ['Trình duyệt', 'Dây cáp', 'Hệ điều hành'],
      difficulty_level: 2,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w207',
      deck_id: '22222222-2222-2222-2222-222222222222',
      term: 'LATENCY',
      phonetic: '/ˈleɪ.tən.si/',
      translation: 'Độ trễ truyền tải',
      example_sentence: 'Low latency is crucial for real-time multiplayer games.',
      example_translation: 'Độ trễ thấp là yếu tố sống còn cho game đối kháng.',
      distractors: ['Tốc độ tải', 'Băng thông', 'Độ phân giải'],
      difficulty_level: 3,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w208',
      deck_id: '22222222-2222-2222-2222-222222222222',
      term: 'QUANTUM',
      phonetic: '/ˈkwɒn.təm/',
      translation: 'Lượng tử',
      example_sentence: 'Quantum computing will revolutionize cryptography.',
      example_translation: 'Điện toán lượng tử sẽ cách mạng hóa mật mã học.',
      distractors: ['Cổ điển', 'Hữu cơ', 'Từ tính'],
      difficulty_level: 4,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
  ],
  '33333333-3333-3333-3333-333333333333': [
    {
      id: 'w301',
      deck_id: '33333333-3333-3333-3333-333333333333',
      term: 'ACCOMMODATION',
      phonetic: '/əˌkɒm.əˈdeɪ.ʃən/',
      translation: 'Chỗ ở, nơi lưu trú',
      example_sentence: 'Hotel accommodation is included in the tour price.',
      example_translation: 'Chỗ ở khách sạn đã bao gồm trong giá tour.',
      distractors: ['Phương tiện', 'Bữa ăn', 'Vé máy bay'],
      difficulty_level: 2,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w302',
      deck_id: '33333333-3333-3333-3333-333333333333',
      term: 'APOLOGIZE',
      phonetic: '/əˈpɒl.ə.dʒaɪz/',
      translation: 'Xin lỗi',
      example_sentence: 'I want to apologize for being late today.',
      example_translation: 'Tôi muốn xin lỗi vì hôm nay đã đến muộn.',
      distractors: ['Cảm ơn', 'Tạm biệt', 'Khen ngợi'],
      difficulty_level: 1,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w303',
      deck_id: '33333333-3333-3333-3333-333333333333',
      term: 'CONVENIENT',
      phonetic: '/kənˈviː.ni.ənt/',
      translation: 'Tiện lợi, thuận tiện',
      example_sentence: 'The subway is a very convenient way to travel around.',
      example_translation: 'Tàu điện ngầm là một cách di chuyển rất tiện lợi.',
      distractors: ['Bất tiện', 'Đắt đỏ', 'Chậm chạp'],
      difficulty_level: 1,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 'w304',
      deck_id: '33333333-3333-3333-3333-333333333333',
      term: 'DESTINATION',
      phonetic: '/ˌdes.tɪˈneɪ.ʃən/',
      translation: 'Điểm đến, đích đến',
      example_sentence: 'Da Nang is a popular travel destination in Vietnam.',
      example_translation: 'Đà Nẵng là điểm đến du lịch nổi tiếng ở Việt Nam.',
      distractors: ['Nơi xuất phát', 'Bản đồ', 'Lịch trình'],
      difficulty_level: 1,
      audio_url: null,
      image_url: null,
      created_at: new Date().toISOString(),
    },
  ],
};
